### ISSUE TITLE
Consumer Key and Consumer Secret

### ISSUE THREAD

**Issue by winbotscript** [jerrydeska/info-covid19-id#1]
Hi sob, salken sebelumnya dan saya ingin tanya mengenai consumer_key and consumer secret karena saya tidak di kasih oleh pihak Twitter nya, apakah ada solusi

Issue Consumer_key and consumer secret :

Consumer Keys
On 01/12/2021 your consumer keys will no longer be visible.
To increase security, make sure to save your keys before they're permanently hidden. Select View keys below and save them somewhere safe.

Tolong dibantu sob mengenai hal diatas

Regards,

WinBot

**Comment by jerrydeska** [comment]
Halo.

Untuk melihat consumer key kamu bisa mengikuti tahap ini:
1. Masuk ke dashboard dan klik simbol kunci pada project app yang kamu buat
2. Klik tombol "View Keys"
3. Setelah di klik akan muncul API Key dan API Key Secret, dimana:
API Key = Consumer Key
API Key Secret = Consumer Secret

Semoga solusi ini dapat membantu!

Regards,

Jerry

**Comment by winbotscript** [comment]
Nanti akan saya coba dan satu lagi sob untuk host = environ['HOST'], saya masukkan localhost kok tidak bisa yah ??? keluar error

Solusinya gmn yah sob ???

Regards,

WinBot

**Comment by jerrydeska** [comment]
Pastikan bahwa MySQL dan salah satu MySQL Driver untuk Python telah terinstall di komputer. Untuk lebih lengkap dapat dilihat di [https://www.w3schools.com/python/python_mysql_getstarted.asp]

Regards,

Jerry

**Comment by winbotscript** [comment]
Hi sob, boleh minta struktur mysqlnya karena masih ketemu error sbb : 

 python covid19ku.py
Connected to MySQL Server version  5.5.5-10.4.13-MariaDB
You're connected to database:  ('corona',)
Mengambil data...
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\mysql\connector\connection_cext.py", line 487, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: Table 'corona.check_case' doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "covid19ku.py", line 358, in <module>
    reply()
  File "covid19ku.py", line 272, in reply
    final_twit = check_indo_case()
  File "covid19ku.py", line 101, in check_indo_case
    check = get_check()
  File "covid19ku.py", line 77, in get_check
    mydb.execute('SELECT * FROM check_case')
  File "C:\Python38\lib\site-packages\mysql\connector\cursor_cext.py", line 264, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "C:\Python38\lib\site-packages\mysql\connector\connection_cext.py", line 491, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'corona.check_case' doesn't exist

Tolong bantuannya yah sib, thanks

Regards,

WinBot

**Comment by jerrydeska** [comment]
Tabel 'corona.check_case' tidak ada di database.

Karena sepertinya jawaban dari isu sudah terjawab maka isu ini akan saya tutup.

Regards,

Jerry
